import React from "react";
import {
  MdAttachMoney,
  MdAddCircle,
  MdDescription,
  MdShoppingCart,
  MdLocalDining,
  MdSportsEsports,
  MdLocalBar,
  MdHome,
  MdDirectionsCar,
  MdMedicalServices,
  MdCheckroom,
  MdSchool,
  MdMoreHoriz,
  MdPayments,
  MdCardGiftcard,
  MdApartment,
  MdFlashOn,
  MdWhatshot,
  MdWater,
  MdSmartphone,
  MdWifi,
  MdAccountBalance,
  MdLocalPizza,
  MdCookie,
  MdTwoWheeler,
  MdRestaurant,
  MdMovie,
  MdGames,
  MdMusicNote,
  MdPlayCircleOutline,
  MdCleaningServices,
  MdWeekend,
  MdLocalFlorist,
  MdLocalLaundryService,
  MdLocalGasStation,
  MdBuild,
  MdCarRepair,
  MdSecurity,
  MdShield,
  MdTaxiAlert,
  MdConfirmationNumber,
  MdHealthAndSafety,
  MdBrush,
  MdContentCut,
  MdFitnessCenter,
  MdDirectionsRun,
  MdWatch,
  MdBook,
  MdLaptopMac,
  MdWork,
  MdMenuBook,
  MdShoppingBasket,
  MdErrorOutline,
  MdEmail,
  MdMailOutline
} from "react-icons/md";

const iconMap: Record<string, React.ElementType> = {
  "cash-plus": MdAttachMoney,
  "file-document-outline": MdDescription,
  "cart-outline": MdShoppingCart,
  "food-outline": MdLocalDining,
  "gamepad-variant-outline": MdSportsEsports,
  "beer-outline": MdLocalBar,
  "home-outline": MdHome,
  "car-outline": MdDirectionsCar,
  "medical-bag": MdMedicalServices,
  "tshirt-crew-outline": MdCheckroom,
  "school-outline": MdSchool,
  "dots-horizontal-circle-outline": MdMoreHoriz,
  "cash-multiple": MdPayments,
  "gift-outline": MdCardGiftcard,
  "home-city-outline": MdApartment,
  "flash-outline": MdFlashOn,
  "fire": MdWhatshot,
  "water-outline": MdWater,
  "cellphone": MdSmartphone,
  "wifi": MdWifi,
  "bank-outline": MdAccountBalance,
  "food-apple-outline": MdLocalPizza,
  "cookie-outline": MdCookie,
  "motorbike": MdTwoWheeler,
  "silverware-fork-knife": MdRestaurant,
  "silverware": MdRestaurant,
  "filmstrip": MdMovie,
  "chess-queen": MdGames,
  "music-circle-outline": MdMusicNote,
  "play-circle-outline": MdPlayCircleOutline,
  "glass-cocktail": MdLocalBar,
  "broom": MdCleaningServices,
  "sofa": MdWeekend,
  "flower-outline": MdLocalFlorist,
  "washing-machine": MdLocalLaundryService,
  "gas-station": MdLocalGasStation,
  "wrench-outline": MdBuild,
  "car-wrench": MdCarRepair,
  "shield-outline": MdSecurity,
  "shield-car": MdShield,
  "taxi": MdTaxiAlert,
  "ticket-outline": MdConfirmationNumber,
  "pill": MdHealthAndSafety,
  "stethoscope": MdHealthAndSafety,
  "lipstick": MdBrush,
  "content-cut": MdContentCut,
  "dumbbell": MdFitnessCenter,
  "shoe-sneaker": MdDirectionsRun,
  "watch-variant": MdWatch,
  "book-outline": MdBook,
  "laptop": MdLaptopMac,
  "account-tie-outline": MdWork,
  "notebook-outline": MdMenuBook,
  "basket-outline": MdShoppingBasket,
  "alert-circle-outline": MdErrorOutline,
  "email-plus-outline": MdEmail,
  "email-outline": MdMailOutline
};

interface Props {
  name: string;
  size?: number;
  color?: string;
}

export const DynamicIcon = ({name, size, color}: Props) => {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null; 
  return <IconComponent size={size} color={color} />;
}
